FROM node:16-alpine as prebuilder

WORKDIR /app

COPY . .

RUN yarn install --immutable --immutable-cache --check-cache

RUN yarn build



FROM node:16-alpine

WORKDIR /app

COPY --from=prebuilder /app ./

EXPOSE 3000

CMD ["yarn", "start:dev"]